import React from 'react';

const Home = () => {
    return (
        <div>
            <p>Home</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Provident quam repellendus harum omnis. Architecto dicta qui voluptatum enim laudantium deserunt, tenetur eligendi voluptatem nisi nobis saepe, vero inventore suscipit assumenda porro illum harum adipisci nesciunt repudiandae. Asperiores, quos! Consequuntur in est quidem eius! Assumenda ducimus placeat accusantium laboriosam fugiat explicabo amet. Rerum, dolores qui! Tenetur facere saepe a cumque ut animi harum architecto suscipit est quaerat, consequuntur voluptas tempore. Aspernatur minima vitae magnam quidem, natus, dolorem quos dicta numquam dolore quae repudiandae temporibus cum explicabo sint atque vero. Sed neque atque aliquam, voluptatum praesentium magnam quia? Ullam tempore dolore temporibus eaque! Accusantium porro labore, aperiam adipisci itaque in nulla amet odit minima sit! Dolor, necessitatibus. Perferendis veritatis similique blanditiis molestiae eius est inventore porro. Atque laudantium cumque aliquam. Cupiditate aliquam aliquid quos quasi, et reiciendis omnis quibusdam reprehenderit culpa vitae dolore, iusto eum libero provident similique hic laboriosam amet pariatur consectetur ullam quisquam veniam? Perferendis facere fuga consequatur repellendus maiores odit quia sequi. Numquam porro, quisquam temporibus accusantium voluptates aut, animi magnam deserunt dicta voluptas aliquam sequi fuga odit ratione quo, autem molestias mollitia neque cum corporis? Modi ducimus obcaecati dolorum doloribus nostrum? Excepturi exercitationem iste voluptas iusto, sint consectetur nostrum doloremque ducimus error dolore reiciendis nihil voluptatem. Non fuga eius, magni cumque impedit, delectus neque ex quas explicabo ipsa id aspernatur culpa, enim eligendi voluptatum? Consectetur modi harum repellendus, cum eligendi aliquam ad, laudantium recusandae, dolor veritatis quae error officiis? Quo quae fugiat est reiciendis placeat repellendus illum natus adipisci, consectetur, nihil eaque molestias nam! Accusantium voluptates optio, consequatur dolor facere nostrum et quo atque cumque dicta deleniti necessitatibus! Reiciendis dolores eveniet nulla ipsa accusantium incidunt explicabo ratione mollitia unde, laborum vitae eos, sed totam voluptatum praesentium. Maiores et nesciunt a voluptas veritatis, fuga ex officiis nisi aliquid beatae vitae facilis, sed explicabo omnis. Ad, explicabo ipsa rerum ut nihil sint excepturi optio vero mollitia laborum tenetur doloribus, dignissimos doloremque possimus! Rerum sunt, qui fugiat in iure eius quaerat, doloribus modi nulla quisquam hic recusandae obcaecati ipsum nostrum! Aspernatur, ipsum, repudiandae modi, autem maiores odit impedit voluptatum quod praesentium laudantium nostrum! Nisi, voluptatibus quo. Repudiandae quas necessitatibus exercitationem repellat magnam enim voluptates labore autem veritatis ipsa qui</p>
        </div>
    );
};

export default Home;